# Generated by Django 5.1.1 on 2024-10-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='disponibilidad',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.usuario'),
        ),
    ]
