# Generated by Django 5.1.1 on 2024-10-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_is_active_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='usuario',
        ),
    ]
