# Generated by Django 5.1.1 on 2024-10-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_servicio_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracion',
            old_name='usuario',
            new_name='usuario_comentario',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuariot'),
        ),
    ]
