# Generated by Django 5.1.1 on 2024-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_usuario_valoracion_usuario_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariot',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariot',
            name='lugar_vivienda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
