# Generated by Django 5.1.1 on 2024-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuariot_edad_usuariot_lugar_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariot',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
