# Generated by Django 5.1.1 on 2024-10-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuariot_edad_usuariot_lugar_vivienda'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatGpt',
        ),
    ]
