# Generated by Django 5.1.1 on 2024-10-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuariot_edad_usuariot_lugar_vivienda'),
        ('chat', '0002_rename_chat_chatgpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgpt',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.servicio'),
            preserve_default=False,
        ),
    ]
